drive.trajectorySequenceBuilder(new Pose2d(-36, -36, Math.toRadians(90))))
	.splineTo(new Vector2d(-36, -12), Math.toRadians(90))
	.turn(Math.toRadians(-0))
	.splineTo(new Vector2d(-12, -12), Math.toRadians(90))
	.turn(Math.toRadians(-0))
	.splineTo(new Vector2d(-12, -36), Math.toRadians(90))
	.turn(Math.toRadians(-0))
	.splineTo(new Vector2d(-36, -36), Math.toRadians(90))
	.turn(Math.toRadians(-0))
	.build();