drive.trajectorySequenceBuilder(new Pose2d(-36, -66, Math.toRadians(90)))
	.lineToLinearHeading(new Pose2d(-30, -36, Math.toRadians(-0)))
	.lineToLinearHeading(new Pose2d(-60, -36, Math.toRadians(180)))
	.waitSeconds(1)
	.splineToConstantHeading(new Vector2d(-24, -60), Math.toRadians(-0))
	.splineToConstantHeading(new Vector2d(24, -60), Math.toRadians(-0))
	.splineToConstantHeading(new Vector2d(48, -36), Math.toRadians(-90))
	.waitSeconds(1)
	.splineTo(new Vector2d(24, -60), Math.toRadians(180))
	.splineTo(new Vector2d(-24, -60), Math.toRadians(180))
	.splineTo(new Vector2d(-60, -36), Math.toRadians(180))
	.waitSeconds(1)
	.splineToConstantHeading(new Vector2d(-24, -60), Math.toRadians(-0))
	.splineToConstantHeading(new Vector2d(24, -60), Math.toRadians(-0))
	.lineToConstantHeading(new Vector2d(48, -36))
	.turn(Math.toRadians(-90))
	.waitSeconds(1)
	.build();